volumes:
  pg_data:

services:
  beauty_salon:
    build: ./beauty_salon/
    env_file: ./beauty_salon/.docker.env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"