# Generated by Django 6.0.3 on 2026-03-11 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название узла')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='Является листом')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.classifier', verbose_name='Родительский узел')),
            ],
            options={
                'verbose_name': 'Классификатор',
                'verbose_name_plural': 'Классификаторы',
                'db_table': 'classifier_node',
            },
        ),
    ]
