# Generated by Django 6.0.3 on 2026-03-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classifier',
            new_name='ClassifierNode',
        ),
        migrations.AlterModelOptions(
            name='classifiernode',
            options={'verbose_name': 'Узел классификатора', 'verbose_name_plural': 'Узлы классификатора'},
        ),
    ]
