# Generated by Django 6.0.3 on 2026-03-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_classifier_classifiernode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiernode',
            name='measuring_unit',
            field=models.CharField(default='штуки', max_length=50, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
