# Generated by Django 6.0.3 on 2026-03-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classifiernode_measuring_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiernode',
            name='measuring_unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения'),
        ),
    ]
