# Generated by Django 6.0.3 on 2026-04-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_measuringunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiernode',
            name='measuring_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.measuringunit', verbose_name='Единица измерения'),
        ),
    ]
