# Generated by Django 6.0.3 on 2026-04-13 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_classifiernode_measuring_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enumeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название перечисления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('measuring_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.measuringunit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Перечисление',
                'verbose_name_plural': 'Перечисления',
                'db_table': 'enumerations',
            },
        ),
    ]
