# Generated by Django 6.0.3 on 2026-04-13 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnumerationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enumeration', verbose_name='Перечисление')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.value', verbose_name='Значение')),
            ],
            options={
                'db_table': 'enumerations_values',
            },
        ),
        migrations.AddField(
            model_name='value',
            name='enumeration',
            field=models.ManyToManyField(related_name='values', through='api.EnumerationValue', to='api.enumeration', verbose_name='Перечисление'),
        ),
    ]
