# Generated by Django 6.0.3 on 2026-04-14 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_enumerationvalue_value_enumeration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='enumeration',
        ),
        migrations.DeleteModel(
            name='EnumerationValue',
        ),
        migrations.AddField(
            model_name='value',
            name='enumeration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='api.enumeration', verbose_name='Перечисление'),
            preserve_default=False,
        ),
    ]
