# Generated by Django 6.0.3 on 2026-04-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_value_enumeration_delete_enumerationvalue_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='value',
            unique_together={('num', 'enumeration')},
        ),
    ]
