# Generated by Django 6.0.3 on 2026-04-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_value_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PictureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/')),
            ],
        ),
        migrations.CreateModel(
            name='RealValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StringValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='enumeration',
            name='value_type',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('real', 'Real'), ('pic', 'Picture')], default=int, max_length=4),
            preserve_default=False,
        ),
    ]
