# Generated by Django 6.0.3 on 2026-04-16 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_intvalue_picturevalue_realvalue_stringvalue_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value',
            name='value_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
