# Generated by Django 6.0.3 on 2026-04-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_value_content_type_value_value_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RealData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='PictureValue',
            new_name='PictureData',
        ),
        migrations.DeleteModel(
            name='IntValue',
        ),
        migrations.DeleteModel(
            name='RealValue',
        ),
        migrations.DeleteModel(
            name='StringValue',
        ),
        migrations.RenameField(
            model_name='enumeration',
            old_name='value_type',
            new_name='data_type',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='value_object_id',
            new_name='data_object_id',
        ),
        migrations.RemoveField(
            model_name='value',
            name='data',
        ),
    ]
