# Generated by Django 6.0.3 on 2026-04-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_intdata_realdata_stringdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiernode',
            name='is_terminal',
            field=models.BooleanField(default=True, verbose_name='Является листом'),
        ),
    ]
