# Generated by Django 6.0.3 on 2026-04-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_classifiernode_is_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumeration',
            name='nodes',
            field=models.ManyToManyField(related_name='enumerations', to='api.classifiernode', verbose_name='Узлы классификатора'),
        ),
    ]
