# Generated by Django 6.0.3 on 2026-04-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_enumeration_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturedata',
            name='image',
            field=models.ImageField(max_length=200, upload_to='pics/'),
        ),
    ]
