# Generated by Django 6.0.3 on 2026-04-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_picturedata_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picturedata',
            old_name='image',
            new_name='data',
        ),
    ]
