# Generated by Django 6.0.3 on 2026-04-18 12:51

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_image_picturedata_data'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='value',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='value',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('num', 'enumeration'), name='unique_num_enumeration_constraint_deferrable'),
        ),
    ]
