# Generated by Django 6.0.3 on 2026-04-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_value_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturedata',
            name='data',
            field=models.URLField(),
        ),
    ]
