# Generated by Django 6.0.3 on 2026-04-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_picturedata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiernode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.classifiernode', verbose_name='Родительский узел'),
        ),
    ]
