# Generated by Django 6.0.3 on 2026-04-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_param_value', models.IntegerField(blank=True, null=True, verbose_name='Минимальное значение')),
                ('max_param_value', models.IntegerField(blank=True, null=True, verbose_name='Максимальное значение')),
                ('classifiernode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classifiernode', verbose_name='Узел классификатора')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parameter', verbose_name='Параметр')),
            ],
            options={
                'db_table': 'parameters_nodes',
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='nodes',
            field=models.ManyToManyField(related_name='parameters', through='api.ParameterNode', to='api.classifiernode', verbose_name='Узлы классификатора'),
        ),
    ]
