# Generated by Django 6.0.3 on 2026-04-28 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_parameternode_parameter_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='measuring_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.measuringunit', verbose_name='Единица измерения'),
        ),
    ]
