# Generated by Django 6.0.3 on 2026-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_service'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parameternode',
            constraint=models.UniqueConstraint(fields=('parameter', 'classifiernode'), name='unique_num_enumeration_constraint'),
        ),
    ]
