# Generated by Django 6.0.3 on 2026-04-30 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_parametervalueservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='enumeration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters_using', to='api.enumeration'),
        ),
    ]
