# Generated by Django 6.0.3 on 2026-04-30 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_parameter_enumeration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametervalueservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='api.service', verbose_name='Услуга'),
        ),
    ]
