# Generated by Django 6.0.3 on 2026-04-30 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_parametervalueservice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametervalueservice',
            name='parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='values_for_services', to='api.parameter', verbose_name='Услуга'),
            preserve_default=False,
        ),
    ]
