# Generated by Django 6.0.3 on 2026-05-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_parametervalueservice_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiernode',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Обозначение'),
        ),
        migrations.AddField(
            model_name='enumeration',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Обозначение'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Обозначение'),
        ),
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Обозначение'),
        ),
    ]
