# Generated by Django 6.0.3 on 2026-05-01 08:32

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_classifiernode_code_enumeration_code_parameter_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Агрегат параметров',
                'verbose_name_plural': 'Агрегаты параметров',
                'db_table': 'parameters_aggregate',
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='aggregate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.parameteraggregate'),
        ),
        migrations.CreateModel(
            name='ParameterAggregateMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Позиция')),
                ('aggregate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parameteraggregate')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parameter')),
            ],
            options={
                'db_table': 'parameters_aggregate_members',
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='aggregates',
            field=models.ManyToManyField(blank=True, related_name='member_parameters', through='api.ParameterAggregateMember', to='api.parameteraggregate'),
        ),
        migrations.AddConstraint(
            model_name='parameteraggregatemember',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('aggregate', 'num'), name='unique_agg_num_deferred'),
        ),
    ]
