# Generated by Django 6.0.3 on 2026-05-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_parameteraggregate_parameter_aggregate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='data_type',
            field=models.CharField(choices=[('int', 'Integer'), ('enum', 'Enumeration'), ('aggregate', 'Aggregate')], max_length=9, verbose_name='Тип данных'),
        ),
    ]
