# Generated by Django 6.0.3 on 2026-05-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_parameter_data_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parameternode',
            name='unique_num_enumeration_constraint',
        ),
        migrations.AddField(
            model_name='parameternode',
            name='num',
            field=models.IntegerField(null=True, verbose_name='Позиция'),
        ),
        migrations.AddConstraint(
            model_name='parameternode',
            constraint=models.UniqueConstraint(fields=('parameter', 'classifiernode'), name='unique_parameter_classifiernode_constraint'),
        ),
        migrations.AddConstraint(
            model_name='parameternode',
            constraint=models.UniqueConstraint(fields=('classifiernode', 'num'), name='unique_classifiernode_num_constraint'),
        ),
    ]
