# Generated by Django 6.0.3 on 2026-05-01 11:51

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_parameternode_unique_num_enumeration_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parameternode',
            name='unique_classifiernode_num_constraint',
        ),
        migrations.AddConstraint(
            model_name='parameternode',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('classifiernode', 'num'), name='unique_classifiernode_num_constraint'),
        ),
    ]
