# Generated by Django 6.0.3 on 2026-05-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_parameternode_unique_classifiernode_num_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameternode',
            name='num',
            field=models.IntegerField(verbose_name='Позиция'),
        ),
    ]
