# Generated by Django 6.0.3 on 2026-05-03 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_parameternode_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='data_type',
            field=models.CharField(choices=[('int', 'Integer'), ('real', 'Real'), ('enum', 'Enumeration'), ('aggregate', 'Aggregate')], max_length=9, verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='parameternode',
            name='classifiernode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters_nodes', to='api.classifiernode', verbose_name='Узел классификатора'),
        ),
        migrations.AlterField(
            model_name='parameternode',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters_nodes', to='api.parameter', verbose_name='Параметр'),
        ),
    ]
