# Generated by Django 6.0.3 on 2026-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_parameter_data_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='aggregates',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='aggregate',
        ),
        migrations.RemoveConstraint(
            model_name='parameteraggregatemember',
            name='unique_agg_num_deferred',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='data_type',
            field=models.CharField(choices=[('int', 'Integer'), ('real', 'Real'), ('enum', 'Enumeration')], max_length=9, verbose_name='Тип данных'),
        ),
        migrations.RemoveField(
            model_name='parameteraggregatemember',
            name='aggregate',
        ),
        migrations.RemoveField(
            model_name='parameteraggregatemember',
            name='parameter',
        ),
        migrations.DeleteModel(
            name='ParameterAggregate',
        ),
        migrations.DeleteModel(
            name='ParameterAggregateMember',
        ),
    ]
