# Generated by Django 6.0.3 on 2026-05-19 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_remove_parameter_aggregates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classifiernode",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="enumeration",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("str", "Строка"),
                    ("int", "Целое число"),
                    ("real", "Вещественное число"),
                    ("pic", "Картинка"),
                ],
                max_length=4,
                verbose_name="Тип данных",
            ),
        ),
        migrations.AlterField(
            model_name="enumeration",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="measuringunit",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("int", "Целое число"),
                    ("real", "Вещественное число"),
                    ("enum", "Перечисление"),
                ],
                max_length=9,
                verbose_name="Тип данных",
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="enumeration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameters_using",
                to="api.enumeration",
                verbose_name="Перечисление",
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
    ]
