# Generated by Django 6.0.3 on 2026-05-13 15:27

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_remove_parameter_aggregates_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationsClassifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="Обозначение",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название узла"),
                ),
            ],
            options={
                "verbose_name": "Класс хозяйственной операции",
                "verbose_name_plural": "Классы хозяйственных операций",
                "db_table": "operations_classifier",
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="Обозначение",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название операции"),
                ),
                (
                    "base_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="api.operationsclassifier",
                        verbose_name="Базовый класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция",
                "verbose_name_plural": "Операции",
                "db_table": "operations",
            },
        ),
        migrations.CreateModel(
            name="ParameterOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_param_value",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Минимальное значение"
                    ),
                ),
                (
                    "max_param_value",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Максимальное значение"
                    ),
                ),
                ("num", models.IntegerField(verbose_name="Позиция")),
                (
                    "operation_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters_operations",
                        to="api.operationsclassifier",
                        verbose_name="Узел классификатора",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters_operations",
                        to="api.parameter",
                        verbose_name="Параметр",
                    ),
                ),
            ],
            options={
                "db_table": "parameters_operation_nodes",
            },
        ),
        migrations.AddField(
            model_name="operationsclassifier",
            name="parameters",
            field=models.ManyToManyField(
                related_name="operations",
                through="api.ParameterOperation",
                to="api.parameter",
                verbose_name="Параметры операции",
            ),
        ),
        migrations.CreateModel(
            name="ParameterValueOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_operations",
                        to="api.operation",
                        verbose_name="Операция",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values_for_operations",
                        to="api.parameter",
                        verbose_name="Параметр",
                    ),
                ),
            ],
            options={
                "db_table": "parameters_operations",
            },
        ),
        migrations.AddConstraint(
            model_name="parameteroperation",
            constraint=models.UniqueConstraint(
                fields=("parameter", "operation_node"),
                name="unique_parameter_operation_node_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="parameteroperation",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("operation_node", "num"),
                name="unique_operation_node_num_constraint",
            ),
        ),
    ]
