# Generated by Django 6.0.3 on 2026-05-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_alter_classifiernode_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameternode",
            name="num",
            field=models.PositiveIntegerField(verbose_name="Позиция"),
        ),
        migrations.AlterField(
            model_name="value",
            name="num",
            field=models.PositiveIntegerField(verbose_name="Позиция"),
        ),
    ]
