# Generated by Django 6.0.3 on 2026-05-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_operationsclassifier_operation_parameteroperation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название категории"),
                ),
            ],
            options={
                "verbose_name": "Категория субъекта",
                "verbose_name_plural": "Категории субъектов",
                "db_table": "subject_category",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название субъекта"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.subjectcategory",
                        verbose_name="Категория субъекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Субъект",
                "verbose_name_plural": "Субъекты",
                "db_table": "subject",
            },
        ),
        migrations.CreateModel(
            name="SubjectOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_operations",
                        to="api.operation",
                        verbose_name="Операция",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects_for_operations",
                        to="api.subject",
                        verbose_name="Параметр",
                    ),
                ),
            ],
            options={
                "db_table": "subjects_operations",
            },
        ),
    ]
