# Generated by Django 6.0.3 on 2026-08-15 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_parameternode_num_alter_value_num"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IntData",
        ),
        migrations.DeleteModel(
            name="PictureData",
        ),
        migrations.DeleteModel(
            name="RealData",
        ),
        migrations.DeleteModel(
            name="StringData",
        ),
        migrations.RemoveField(
            model_name="parametervalueservice",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="parametervalueservice",
            name="data_object_id",
        ),
        migrations.RemoveField(
            model_name="value",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="value",
            name="data_object_id",
        ),
        migrations.AddField(
            model_name="parametervalueservice",
            name="value",
            field=models.CharField(default="Deprecated", verbose_name="Значение"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="value",
            name="data",
            field=models.CharField(default="Deprecated", verbose_name="Данные"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parameternode",
            name="num",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Позиция",
            ),
        ),
        migrations.AlterField(
            model_name="value",
            name="num",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Позиция",
            ),
        ),
    ]
