# Generated by Django 6.0.3 on 2026-05-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_subjectcategory_subject_subjectoperation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametervalueoperation",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_parameters",
                to="api.operation",
                verbose_name="Операция",
            ),
        ),
        migrations.AlterField(
            model_name="parametervalueoperation",
            name="parameter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations_for_parameter",
                to="api.parameter",
                verbose_name="Параметр",
            ),
        ),
        migrations.AlterField(
            model_name="subjectoperation",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects_for_operations",
                to="api.operation",
                verbose_name="Операция",
            ),
        ),
        migrations.AlterField(
            model_name="subjectoperation",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_operations",
                to="api.subject",
                verbose_name="Параметр",
            ),
        ),
        migrations.CreateModel(
            name="ServicesOperations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_operations",
                        to="api.operation",
                        verbose_name="Операция",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations_for_subject",
                        to="api.service",
                        verbose_name="Параметр",
                    ),
                ),
            ],
            options={
                "db_table": "services_operations",
            },
        ),
    ]
