# Generated by Django 6.0.3 on 2026-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_alter_parametervalueoperation_operation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название роли"),
                ),
            ],
            options={
                "verbose_name": "Роль субъекта",
                "verbose_name_plural": "Роли субъектов",
                "db_table": "subject_role",
            },
        ),
    ]
