# Generated by Django 6.0.3 on 2026-09-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_standardnode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="base_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="api.standardnode",
                verbose_name="Базовый класс",
            ),
        ),
    ]
