# Generated by Django 6.0.3 on 2026-05-13 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_subjectrole"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="subjectrole",
            table="subject_roles",
        ),
        migrations.CreateModel(
            name="RolesOperations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_roles",
                        to="api.operation",
                        verbose_name="Операция",
                    ),
                ),
                (
                    "subject_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="api.subjectrole",
                        verbose_name="Параметр",
                    ),
                ),
            ],
            options={
                "db_table": "subject_roles_operations",
            },
        ),
    ]
