# Generated by Django 6.0.3 on 2026-09-24 09:12

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_alter_service_base_class"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="parameternode",
            name="unique_parameter_classifiernode_constraint",
        ),
        migrations.RemoveConstraint(
            model_name="parameternode",
            name="unique_classifiernode_num_constraint",
        ),
        migrations.AddField(
            model_name="parameternode",
            name="standardnode",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameters_nodes",
                to="api.standardnode",
                verbose_name="Типовой класс",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parameter",
            name="nodes",
            field=models.ManyToManyField(
                related_name="parameters",
                through="api.ParameterNode",
                to="api.standardnode",
                verbose_name="Типовые классы",
            ),
        ),
        migrations.AddConstraint(
            model_name="parameternode",
            constraint=models.UniqueConstraint(
                fields=("parameter", "standardnode"),
                name="unique_parameter_standardnode_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="parameternode",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("standardnode", "num"),
                name="unique_standardnode_num_constraint",
            ),
        ),
        migrations.RemoveField(
            model_name="parameternode",
            name="classifiernode",
        ),
    ]
