# Generated by Django 6.0.3 on 2026-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_alter_subjectrole_table_rolesoperations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicesoperations",
            name="operation",
        ),
        migrations.RemoveField(
            model_name="servicesoperations",
            name="service",
        ),
        migrations.RemoveField(
            model_name="subjectoperation",
            name="operation",
        ),
        migrations.RemoveField(
            model_name="subjectoperation",
            name="subject",
        ),
        migrations.AddField(
            model_name="operation",
            name="operations",
            field=models.ManyToManyField(
                db_table="services_operations",
                related_name="operations",
                to="api.service",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="operations",
            field=models.ManyToManyField(
                db_table="subjects_operations",
                related_name="subjects",
                to="api.operation",
            ),
        ),
        migrations.AddField(
            model_name="subjectrole",
            name="operations",
            field=models.ManyToManyField(
                db_table="subject_roles_operation_nodes",
                related_name="subject_roles",
                to="api.operationsclassifier",
            ),
        ),
        migrations.DeleteModel(
            name="RolesOperations",
        ),
        migrations.DeleteModel(
            name="ServicesOperations",
        ),
        migrations.DeleteModel(
            name="SubjectOperation",
        ),
    ]
