# Generated by Django 6.0.3 on 2026-05-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_remove_servicesoperations_operation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название роли"),
                ),
                (
                    "operations",
                    models.ManyToManyField(
                        db_table="document_roles_operation_nodes",
                        related_name="document_roles",
                        to="api.operationsclassifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль документа",
                "verbose_name_plural": "Роли документов",
                "db_table": "document_roles",
            },
        ),
    ]
