# Generated by Django 6.0.3 on 2026-05-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_document_documentservice_document_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operation",
            old_name="operations",
            new_name="services",
        ),
        migrations.RemoveField(
            model_name="document",
            name="service",
        ),
        migrations.AddField(
            model_name="document",
            name="services",
            field=models.ManyToManyField(
                related_name="documents",
                through="api.DocumentService",
                to="api.service",
            ),
        ),
        migrations.AlterField(
            model_name="documentservice",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.document"
            ),
        ),
        migrations.AlterField(
            model_name="documentservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.service"
            ),
        ),
        migrations.AlterField(
            model_name="parameteroperation",
            name="operation_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.operationsclassifier",
                verbose_name="Узел классификатора",
            ),
        ),
        migrations.AlterField(
            model_name="parameteroperation",
            name="parameter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.parameter",
                verbose_name="Параметр",
            ),
        ),
    ]
