# Generated by Django 6.0.3 on 2026-05-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_rename_operations_operation_services_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentrole",
            name="operations",
            field=models.ManyToManyField(
                blank=True,
                db_table="document_roles_operation_nodes",
                related_name="document_roles",
                to="api.operationsclassifier",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                db_table="services_operations",
                related_name="operations",
                to="api.service",
            ),
        ),
        migrations.AlterField(
            model_name="operationsclassifier",
            name="parameters",
            field=models.ManyToManyField(
                blank=True,
                related_name="operations",
                through="api.ParameterOperation",
                to="api.parameter",
                verbose_name="Параметры операции",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="operations",
            field=models.ManyToManyField(
                blank=True,
                db_table="subjects_operations",
                related_name="subjects",
                to="api.operation",
            ),
        ),
        migrations.AlterField(
            model_name="subjectrole",
            name="operations",
            field=models.ManyToManyField(
                blank=True,
                db_table="subject_roles_operation_nodes",
                related_name="subject_roles",
                to="api.operationsclassifier",
            ),
        ),
    ]
