# Generated by Django 6.0.3 on 2026-05-13 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_alter_documentrole_operations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="services",
        ),
        migrations.DeleteModel(
            name="DocumentService",
        ),
        migrations.CreateModel(
            name="OperationService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.operation"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.service"
                    ),
                ),
            ],
            options={
                "db_table": "operations_services",
            },
        ),
        migrations.AddField(
            model_name="operation",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="operations",
                through="api.OperationService",
                to="api.service",
            ),
        ),
    ]
