# Generated by Django 6.0.3 on 2026-05-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_remove_document_services_operationservice_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="subjectcategory",
            table="subject_categories",
        ),
    ]
