# Generated by Django 6.0.3 on 2026-05-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_alter_subjectcategory_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="subjects",
        ),
    ]
