# Generated by Django 6.0.3 on 2026-05-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_remove_document_subjects"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="subject",
            table="subjects",
        ),
    ]
